# This playbook is used to configure dataguard for 19c.
# Before executing this playbook, please refer the documentation inside the docs directory.
#
# - hosts: all_nodes                     # Provide the name of the target lpar registered in ansible inventory.
#  remote_user: oracle                     # This needs to be run by "oracle" user.
#  gather_facts: False
#  vars_files:
#      - vars/dataguard/dataguard_vars.yml  # update all the required variables
#      - vars/vault.yml       # update the passwords


- name: Configure Data Guard for 19c
  hosts: all
  remote_user: "{{ db_oracle_user }}"
  gather_facts: false
  vars_files:
    - vars/dataguard/dataguard_vars.yml
    - vars/vault.yml

  roles:
    - role: dataguard_precheck
      tags: dataguard_precheck

    - role: primary_config
      tags: primary_config

    - role: standby_config
      tags: standby_config

    - role: create_standby
      tags: create_standby

    - role: post_sync_check
      tags: post_sync_check
